### ISSUE TITLE
Error fetching priority fee estimate on devnet

### ISSUE THREAD

**Issue by hassanshafique** [helius-labs/helius-sdk#151]
Error:
```
Error fetching priority fee estimate: AxiosError: Request failed with status code 400
    at RpcClient.<anonymous> (/path/to/project/node_modules/helius-sdk/dist/src/RpcClient.js:608:23)
    at Generator.throw (<anonymous>)
    at rejected (/path/to/project/node_modules/helius-sdk/dist/src/RpcClient.js:6:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
The Priority fee API works on `mainnet`

**Comment by 0xIchigo** [comment]
gm! Unfortunately, the `getPriorityFeeEstimate` method does not work on devnet at this time
